services:
  db:
    build:
      context: ./postgresql
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=transcendence
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build:
      context: ./django
    container_name: django
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./django:/app
      - static_volume:/app/staticfiles
    environment:
      - DJANGO_SETTINGS_MODULE=transcendence.settings
    command: daphne -b 0.0.0.0 -p 8000 transcendence.asgi:application
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
  

volumes:
  db_data:
  static_volume:
