# Generated by Django 4.2.20 on 2025-03-26 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0001_initial'),
    ]

    operations = [
    ]
