# Generated by Django 4.2.19 on 2025-02-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='trivial',
            field=models.BooleanField(default=True),
        ),
    ]
