# Generated by Django 4.2.19 on 2025-02-10 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0002_auto_20250210_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='temp_field',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='trivial',
        ),
    ]
