# Generated by Django 4.2.20 on 2025-03-16 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0002_player'),
        ('transcendence', '0005_match_matchmaking'),
    ]

    operations = [
    ]
